// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryStoragePosition {
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub node: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryAddFileRequest {
    #[prost(message, optional, tag = "1")]
    pub repository_storage_position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub branch: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryAddFilesResponse {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositorySyncBranchResponse {
    #[prost(message, repeated, tag = "1")]
    pub branches: ::prost::alloc::vec::Vec<RepositoryBranch>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryCreateBranchRequest {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub from: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryDeleteBranchRequest {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryReNameBranchRequest {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositorySyncCommitResponse {
    #[prost(message, repeated, tag = "1")]
    pub commits: ::prost::alloc::vec::Vec<RepositoryCommit>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryBranch {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub head: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub commit_nums: i32,
    #[prost(string, optional, tag = "4")]
    pub from: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub to: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub start: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryCommit {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub branch: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub file_nums: i32,
    #[prost(message, repeated, tag = "8")]
    pub tree: ::prost::alloc::vec::Vec<RepositoryTree>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryTree {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryFileResponse {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub mode: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryFileRequest {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryTagsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<RepositoryTags>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryTags {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hash: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub date: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryCommitRequest {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<RepositoryStoragePosition>,
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod rep_repository_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RepRepositoryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RepRepositoryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RepRepositoryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RepRepositoryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RepRepositoryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryStoragePosition>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "Create"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryStoragePosition>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/Delete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "Delete"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn add_file(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryAddFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryAddFilesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/AddFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "AddFile"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sync_branch(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositorySyncBranchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/SyncBranch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "SyncBranch"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sync_commit(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryCommitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositorySyncCommitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/SyncCommit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "SyncCommit"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sync_blob(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/SyncBlob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "SyncBlob"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sync_tags(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryTagsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/SyncTags",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "SyncTags"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_branch(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryCreateBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/CreateBranch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "CreateBranch"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_branch(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryDeleteBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/DeleteBranch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "DeleteBranch"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn re_name_branch(
            &mut self,
            request: impl tonic::IntoRequest<super::RepositoryReNameBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core_git.RepRepository/ReNameBranch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("core_git.RepRepository", "ReNameBranch"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod rep_repository_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RepRepositoryServer.
    #[async_trait]
    pub trait RepRepository: std::marker::Send + std::marker::Sync + 'static {
        async fn create(
            &self,
            request: tonic::Request<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryStoragePosition>,
            tonic::Status,
        >;
        async fn delete(
            &self,
            request: tonic::Request<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryStoragePosition>,
            tonic::Status,
        >;
        async fn add_file(
            &self,
            request: tonic::Request<super::RepositoryAddFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryAddFilesResponse>,
            tonic::Status,
        >;
        async fn sync_branch(
            &self,
            request: tonic::Request<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositorySyncBranchResponse>,
            tonic::Status,
        >;
        async fn sync_commit(
            &self,
            request: tonic::Request<super::RepositoryCommitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositorySyncCommitResponse>,
            tonic::Status,
        >;
        async fn sync_blob(
            &self,
            request: tonic::Request<super::RepositoryFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryFileResponse>,
            tonic::Status,
        >;
        async fn sync_tags(
            &self,
            request: tonic::Request<super::RepositoryStoragePosition>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryTagsResponse>,
            tonic::Status,
        >;
        async fn create_branch(
            &self,
            request: tonic::Request<super::RepositoryCreateBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        >;
        async fn delete_branch(
            &self,
            request: tonic::Request<super::RepositoryDeleteBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        >;
        async fn re_name_branch(
            &self,
            request: tonic::Request<super::RepositoryReNameBranchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RepositoryBranch>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct RepRepositoryServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RepRepositoryServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RepRepositoryServer<T>
    where
        T: RepRepository,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/core_git.RepRepository/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryStoragePosition>
                    for CreateSvc<T> {
                        type Response = super::RepositoryStoragePosition;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryStoragePosition>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/Delete" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryStoragePosition>
                    for DeleteSvc<T> {
                        type Response = super::RepositoryStoragePosition;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryStoragePosition>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/AddFile" => {
                    #[allow(non_camel_case_types)]
                    struct AddFileSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryAddFileRequest>
                    for AddFileSvc<T> {
                        type Response = super::RepositoryAddFilesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryAddFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::add_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/SyncBranch" => {
                    #[allow(non_camel_case_types)]
                    struct SyncBranchSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryStoragePosition>
                    for SyncBranchSvc<T> {
                        type Response = super::RepositorySyncBranchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryStoragePosition>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::sync_branch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncBranchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/SyncCommit" => {
                    #[allow(non_camel_case_types)]
                    struct SyncCommitSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryCommitRequest>
                    for SyncCommitSvc<T> {
                        type Response = super::RepositorySyncCommitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryCommitRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::sync_commit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncCommitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/SyncBlob" => {
                    #[allow(non_camel_case_types)]
                    struct SyncBlobSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryFileRequest>
                    for SyncBlobSvc<T> {
                        type Response = super::RepositoryFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::sync_blob(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncBlobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/SyncTags" => {
                    #[allow(non_camel_case_types)]
                    struct SyncTagsSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryStoragePosition>
                    for SyncTagsSvc<T> {
                        type Response = super::RepositoryTagsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryStoragePosition>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::sync_tags(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncTagsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/CreateBranch" => {
                    #[allow(non_camel_case_types)]
                    struct CreateBranchSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryCreateBranchRequest>
                    for CreateBranchSvc<T> {
                        type Response = super::RepositoryBranch;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryCreateBranchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::create_branch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateBranchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/DeleteBranch" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteBranchSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryDeleteBranchRequest>
                    for DeleteBranchSvc<T> {
                        type Response = super::RepositoryBranch;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryDeleteBranchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::delete_branch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteBranchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/core_git.RepRepository/ReNameBranch" => {
                    #[allow(non_camel_case_types)]
                    struct ReNameBranchSvc<T: RepRepository>(pub Arc<T>);
                    impl<
                        T: RepRepository,
                    > tonic::server::UnaryService<super::RepositoryReNameBranchRequest>
                    for ReNameBranchSvc<T> {
                        type Response = super::RepositoryBranch;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RepositoryReNameBranchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RepRepository>::re_name_branch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReNameBranchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RepRepositoryServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "core_git.RepRepository";
    impl<T> tonic::server::NamedService for RepRepositoryServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
