//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod aksks;
pub mod branches;
pub mod bun_migration_locks;
pub mod bun_migrations;
pub mod commits;
pub mod groups;
pub mod members;
pub mod merge_requests;
pub mod policies;
pub mod repositories;
pub mod tags;
pub mod trees;
pub mod usergroup;
pub mod users;
pub mod wips;
mod filemode;
mod migrations;
