//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use sea_orm::FromJsonQueryResult;
use serde::{Deserialize, Serialize, Serializer};
use serde::ser::SerializeStruct;
use crate::model::filemode::FileMode;
use crate::utils::hash::Hasher;



#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trees")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "VarBinary(StringLen::None)"
    )]
    pub hash: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub repository_id: Uuid,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub check_sum: Hasher,
    pub r#type: i16,
    pub size: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub properties: Property,
    #[sea_orm(column_type = "JsonBinary")]
    pub sub_objects: Vec<TreeEntry>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Clone,Debug,PartialEq,Eq,Serialize,Deserialize,FromJsonQueryResult)]
pub struct Property{
    mode: FileMode
}

#[derive(Clone,Debug,PartialEq,Eq,Serialize,Deserialize,FromJsonQueryResult)]
pub struct TreeEntry{
    pub name: String,
    pub id_dir: bool,
    pub hash: Hasher,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Serialize for Model {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer
    {
        let mut s = serializer
            .serialize_struct("Trees", 3 + self.sub_objects.len())?;
        s.serialize_field("hash", &Hasher(self.hash.clone()).hex())?;
        s.serialize_field("repository_id", &self.repository_id)?;
        s.serialize_field("check_sum", &self.check_sum)?;
        s.serialize_field("type", &self.r#type)?;
        s.serialize_field("properties", &self.properties)?;
        s.serialize_field("sub_objects", &self.sub_objects)?;
        s.serialize_field("created_at", &self.created_at)?;
        s.serialize_field("updated_at", &self.updated_at)?;
        s.end()
    }
}