//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wips")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub current_tree: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub base_commit: Vec<u8>,
    pub repository_id: Uuid,
    pub ref_id: Uuid,
    pub state: i64,
    pub creator_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
