[package]
name = "jzfs_module"
version = "0.1.0"
edition = "2021"

[dependencies.jzfs_entity]
path = "../entity"

[dependencies.jzfs_service]
path = "../service"


[dependencies]
async-trait = "0.1.83"
sha256 = { version = "1.5.0",features = ["tokio"] }