[http]
port = 6080
host = "0.0.0.0"
workers = 12


[database.auth]
hostname = "221.128.225.26"
port = 5432
username = "postgres"
password = "1.2.3.4.5.6."
database = "auth"
pool = 4

[database.repo]
hostname = "221.128.225.26"
port = 5432
username = "1.2.3.4.5.6."
password = "123456"
database = "repo"
pool = 4


[redis]
host = "221.128.225.26"
port = 6379