[http]
port = 34513
host = "0.0.0.0"
workers = 12


[database.auth]
hostname = "localhost"
port = 5432
username = "postgres"
password = "123456"
database = "auth"
pool = 4


[redis]
host = "localhost"
port = 6379