name: Build Test
on:
  push:
    branches:
      - main
      - deploy/*
  pull_request:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      KUBECONTENT:
        required: true


jobs:
  deployment:
    if: ${{ startsWith(github.ref, 'refs/heads/deployment/') || github.ref == 'refs/heads/main'  }}
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"    
            echo "::set-output name=version::${{ github.sha }}"
          fi

      - name: Build and push
        run: |
          docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t gitdatateam/jzfs-rs:${{ steps.version.outputs.version }} . 
          docker push gitdatateam/jzfs-rs:${{ steps.version.outputs.version }}

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: /usr/sbin/helm upgrade jzfs-rs --install ./chart/ --namespace gitdata --set-string tag=${{ steps.version.outputs.version }}
          kubeconfig: ${{ secrets.KUBECONTENT }}
          overrule_existing_kubeconfig: "true"
